INSERT INTO Teacher(name, email, password, is_teacher) VALUES ('Andreas','andreasn@cs.helsinki.fi','$2a$12$jNvUghmzXObxcfycqofQveqrk3P59kN.UD7REwxK34dbEv.R5PV/W',true);
INSERT INTO Teacher(name, email, password, is_teacher) VALUES ('Ohjaaja','ohjaaja@ohjaajat.fi','$2a$12$OTz4ngjLtCB3U8onkyDYmeXDl/e/oIJmrWarfQKlbReP9f.wELeAu',false);

INSERT INTO Course (name, term) VALUES ('Johdatus yliopistomatematiikkaan', 'Syksy 2016');
INSERT INTO Course (name, term) VALUES ('Topologia I', 'Syksy 2016');

INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010001','A001-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010002','A002-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010003','A003-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010004','A004-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010005','A005-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010006','A006-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010007','A007-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010008','A008-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010009','A009-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010010','A010-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010011','A011-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010012','A012-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010013','A013-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('014010014','A014-AAA',1);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010001','B001-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010002','B002-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010003','B003-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010004','B004-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010005','B005-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010006','B006-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010007','B007-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010008','B008-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010009','B009-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010010','B010-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010011','B011-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010012','B012-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010013','B013-AAA',2);
INSERT INTO Student (student_number, course_number, course_id) VALUES ('015010014','B014-AAA',2);

INSERT INTO Exercise (exercise_number, number_of_problems, number_of_star_problems, max_non_star_score, max_star_score, course_id) VALUES (1,15,1,12,1,1);
INSERT INTO Exercise (exercise_number, number_of_problems, number_of_star_problems, max_non_star_score, max_star_score, course_id) VALUES (2,15,1,13,1,1);
INSERT INTO Exercise (exercise_number, number_of_problems, number_of_star_problems, max_non_star_score, max_star_score, course_id) VALUES (1,15,1,12,1,2);
INSERT INTO Exercise (exercise_number, number_of_problems, number_of_star_problems, max_non_star_score, max_star_score, course_id) VALUES (2,15,1,13,1,2);

INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('1',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('2',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('3',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('4',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('5',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('6',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('7',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('8',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('9',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('10',true,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('11',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('12',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('13',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('14',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('15',false,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('10k1',true,1);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('10k2',true,1);

INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('1',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('2',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('3',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('4',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('5',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('6',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('7',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('8',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('9',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('10',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('11',true,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('12',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('13',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('14',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('15',false,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('11k1',true,2);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('11k2',true,2);

INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('1',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('2',true,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('3',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('4',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('5',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('6',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('7',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('8',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('9',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('10',true,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('11',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('12',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('13',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('14',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('15',false,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('2k1',true,3);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('2k2',true,3);

INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('1',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('2',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('3',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('4',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('5',true,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('6',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('7',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('8',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('9',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('10',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('11',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('12',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('13',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('14',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('15',false,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('5k1',true,4);
INSERT INTO Problem (problem_number, star_problem, exercise_id) VALUES ('5k2',true,4);