DROP TABLE IF EXISTS ProblemReturn CASCADE;
DROP TABLE IF EXISTS Problem CASCADE;
DROP TABLE IF EXISTS Exercise CASCADE;
DROP TABLE IF EXISTS Student CASCADE;
DROP TABLE IF EXISTS Instructor CASCADE;
DROP TABLE IF EXISTS Course CASCADE;
DROP TABLE IF EXISTS Teacher CASCADE;